docker-compose-yaml: docker-compose.yml

tasks:
  post-deploy:
    - run:
        name: drush cim
        command: cd web && drush -y cim
        service: cli
    - run:
        name: drush cr
        command: cd web && drush -y cr
        service: cli