docker-compose-yaml: docker-compose.yml

tasks:
  post-deploy:
    - run:
        name: IF no Drupal installed drush si with no email sending
        command: |
            cd docroot
            if [[ $(drush core-status bootstrap --pipe) == "" ]]; then
                # no drupal installed, we install drupal from scratch
                drush -y si config_installer -y --account-name=admin --account-pass=admin install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
            fi
        service: cli
    - run:
        name: drush cim
        command: cd web && drush -y cim
        service: cli
    - run:
        name: drush cr
        command: cd web && drush -y cr
        service: cli