ARG CLI_IMAGE
FROM ${CLI_IMAGE:-builder} as builder

FROM amazeeio/nginx-drupal

COPY .lagoon/nginx-drupal-cors.conf /etc/nginx/conf.d/drupal/location_drupal_prepend.conf

COPY --from=builder /app /app

ENV WEBROOT=web
