ARG CLI_IMAGE
FROM ${CLI_IMAGE:-builder} as builder

FROM amazeeio/centos7-nginx-drupal:1.12

COPY .amazeeio/drupal.conf /etc/nginx/sites/drupal.conf
RUN fix-permissions /etc/nginx/sites/drupal.conf

COPY --from=builder /app /app

ENV WEBROOT=web
